[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/%E8%A8%AA%E5%95%8F%E4%BB%8B%E8%AD%B7/"
to = "/houmon"
status = 301

[[redirects]]
from = "/%E4%BB%8B%E8%AD%B7%E4%BF%9D%E9%99%BA%E3%82%BF%E3%82%AF%E3%82%B7%E3%83%BC/"
to = "/taxi"
status = 301

[[redirects]]
from = "/%E4%B8%80%E8%88%AC%E4%BB%8B%E8%AD%B7%E3%82%BF%E3%82%AF%E3%82%B7%E3%83%BC/"
to = "/taxi"
status = 301
